# Generated by Django 3.1.3 on 2024-04-02 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_start', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Types',
        ),
    ]
