# Generated by Django 3.1.3 on 2024-04-05 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_start', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='trait_A_score',
        ),
        migrations.RemoveField(
            model_name='question',
            name='trait_B_score',
        ),
        migrations.RemoveField(
            model_name='question',
            name='trait_C_score',
        ),
    ]
